### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by kdeldycke** [kdeldycke/maildir-deduplicate#25]
Old script runs, but is not very clear on what it's doing. It did give me something wrong after a run on some Maildir:

     Traceback (most recent call last):
       File "./maildir-deduplicate.py", line 204, in <module>
         main()
       File "./maildir-deduplicate.py", line 200, in main
        duplicates = findDuplicates(mails_by_hash, delete)
       File "./maildir-deduplicate.py", line 107, in findDuplicates
        subject, count = re.subn('\s+', ' ', subject)
       File "/usr/lib64/python2.6/re.py", line 162, in subn
        return _compile(pattern, 0).subn(repl, string, count)
      TypeError: expected string or buffer
  
Reported by @jult at https://github.com/kdeldycke/maildir-deduplicate/issues/21#issuecomment-141473525

**Comment by kdeldycke** [comment]
Message hashing and decoding has been heavily updated in the last few months. This issue might have been fixed since then. Let's close it.
