### ISSUE TITLE
AttributeError: Message instance has no attribute 'get_all'

### ISSUE THREAD

**Issue by brianmay** [kdeldycke/maildir-deduplicate#28]
Not having much luck getting this to work:

```
Traceback (most recent call last):
  File "/tmp/python/bin/mdedup", line 9, in <module>
    load_entry_point('maildir-deduplicate==1.0.1.dev0', 'console_scripts', 'mdedup')()
  File "/tmp/python/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/python/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/tmp/python/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/python/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/python/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/tmp/python/local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/maildir-deduplicate/maildir_deduplicate/cli.py", line 137, in deduplicate
    dedup.add_maildir(maildir)
  File "/tmp/maildir-deduplicate/maildir_deduplicate/deduplicate.py", line 72, in add_maildir
    mail_file, message, self.use_message_id)
  File "/tmp/maildir-deduplicate/maildir_deduplicate/deduplicate.py", line 95, in compute_hash
    canonical_headers_text = cls.canonical_headers(mail_file, message)
  File "/tmp/maildir-deduplicate/maildir_deduplicate/deduplicate.py", line 115, in canonical_headers
    for value in mail.get_all(header):
AttributeError: Message instance has no attribute 'get_all'
```

**Comment by brianmay** [comment]
Got the same issue with the version from PyPI too.

**Comment by davidbartonau** [comment]
I am experiencing the same on an Ubuntu 12.04 server.  It is using python 2.7, although 3.4 is also available.

**Comment by mnalis** [comment]
same bug on Debian Wheezy, via `pip install maildir-deduplicate`

**Comment by mcgrof** [comment]
get_all() is part of the email.message package so upon inspecting the only thing I can think of is a sort of incompatibility between Python versions here. I was not abl eto fix this but the legacy branch works well if you ran into this, its a standalone single Python file.

**Comment by brianmay** [comment]
I think I concluded it isn't a email.message - from memory it is rfc822.message which does not have a get_all() function. I speculate getheader() is required, however I changed this and encountered more errors.

**Comment by brianmay** [comment]
From https://docs.python.org/2/library/mailbox.html#mailbox.Maildir: "It is for historical reasons that factory defaults to rfc822.Message and that dirname is named as such rather than path. For a Maildir instance that behaves like instances of other Mailbox subclasses, set factory to None."

**Comment by kdeldycke** [comment]
I don't have much time to dedicate to this project but if you find a way to fix this issue feel free to send a PR. I'll be happy to merge it and release a new version of the package.

**Comment by Painted-Fox** [comment]
I run NixOS and ran into this problem.  Thank you, @brianmay for researching this issue.  I tried your solution and found that setting factory to None does resolve this.

**Comment by kdeldycke** [comment]
Just merge @Painted-Fox pull request. I'll release a new version on PyPi soon.

**Comment by kdeldycke** [comment]
FYI, v1.0.2 has been released: https://pypi.python.org/pypi/maildir-deduplicate/1.0.2
