### ISSUE TITLE
Assertion Error at deduplicate.py:596

### ISSUE THREAD

**Issue by zx80** [kdeldycke/maildir-deduplicate#45]
Failed assert on developer version:

```
Traceback (most recent call last):
  File "/usr/local/bin/mdedup", line 9, in <module>
    load_entry_point('maildir-deduplicate==2.0.2', 'console_scripts', 'mdedup')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/maildir_deduplicate/cli.py", line 196, in deduplicate
  File "build/bdist.linux-x86_64/egg/maildir_deduplicate/deduplicate.py", line 596, in report
AssertionError
```

**Comment by kdeldycke** [comment]
Seems to be that line: https://github.com/kdeldycke/maildir-deduplicate/blob/f710ca41bec58389bbd4f1f737bbd418905f23fd/maildir_deduplicate/deduplicate.py#L596 .

But that's odd. Can you provide me with a full trace of execution in debug mode?

**Comment by tomrittervg** [comment]
I have a very similar problem, the trace is here: http://paste2.org/JXLxDVGa
I am using the current develop branch.

**Comment by jefftemplon** [comment]
I have the same issue.  Also the stats are very weird, it sees 2557 mails and also 2557 duplicates, which disagrees with later info printed by the program, in any case there are certainly less than 2557 duplicates.

**Comment by jefftemplon** [comment]
I just ran it on a reasonably uncomplicated Maildir; here you can see what I mean.  The stats seem very wrong (or the metrics that are being printed have non-intuitive definitions!)

```
╒════════════╤══════════╕
│ Mails      │   Metric │
╞════════════╪══════════╡
│ Found      │     1528 │
├────────────┼──────────┤
│ Skipped    │        0 │
├────────────┼──────────┤
│ Rejected   │        0 │
├────────────┼──────────┤
│ Kept       │     1528 │
├────────────┼──────────┤
│ Unique     │     1183 │
├────────────┼──────────┤
│ Duplicates │     1528 │
├────────────┼──────────┤
│ Deleted    │        8 │
╘════════════╧══════════╛
╒══════════════════════════════════════╤══════════╕
│ Duplicate sets                       │   Metric │
╞══════════════════════════════════════╪══════════╡
│ Total                                │     1326 │
├──────────────────────────────────────┼──────────┤
│ Ignored                              │     1183 │
├──────────────────────────────────────┼──────────┤
│ Skipped                              │       19 │
├──────────────────────────────────────┼──────────┤
│ Rejected (bad encoding)              │        8 │
├──────────────────────────────────────┼──────────┤
│ Rejected (too dissimilar in size)    │       86 │
├──────────────────────────────────────┼──────────┤
│ Rejected (too dissimilar in content) │       22 │
├──────────────────────────────────────┼──────────┤
│ Deduplicated                         │        8 │
╘══════════════════════════════════════╧══════════╛
```

**Comment by kdeldycke** [comment]
Issue has been fixed upstream by the merge of https://github.com/kdeldycke/maildir-deduplicate/pull/64.
