### ISSUE TITLE
AttributeError: 'module' object has no attribute 'init' on startup

### ISSUE THREAD

**Issue by mistrey** [kdeldycke/maildir-deduplicate#58]
To reproduce:

```
mdedup --help
```
results in
```
Traceback (most recent call last):
  File "/usr/bin/mdedup", line 7, in <module>
    from maildir_deduplicate.cli import cli
  File "/usr/lib/python3.6/site-packages/maildir_deduplicate/cli.py", line 51, in <module>
    @click_log.init(logger)
AttributeError: module 'click_log' has no attribute 'init'
```

Cause:

The user interface of click_log has changed in version 0.2.0.
[See](https://github.com/click-contrib/click-log/commit/e26170d8f40a4817a9178582d02248c1f082a32e#diff-816fea608d9f0e59fdac1ca0496203b3)

**Comment by bdillahu** [comment]
Looks like you can change:

/usr/lib/python3.6/site-packages/maildir_deduplicate/cli.py

Line: 51 and 52:
#@click_log.init(logger)
@click_log.simple_verbosity_option(logger,
    default='INFO', metavar='LEVEL',
    help='Either CRITICAL, ERROR, WARNING, INFO or DEBUG. Defaults to INFO.')

**Comment by mistrey** [comment]
Thanks bdillahu,

I made changes in cli.py and deduplicate.py in the spirit of [this project](https://github.com/pimutils/vdirsyncer/search?utf8=✓&q=log&type=). Now the script is running and showing all log entries until I finally run into [#57](https://github.com/kdeldycke/maildir-deduplicate/issues/57) :-(

**Comment by bdillahu** [comment]
Yeah, I commented out the one assert that it was failing on, but I'm not really sure that is 1) safe, and 2) working... I haven't had much time to test since then.

**Comment by mistrey** [comment]
Neither safe nor working. It just blocks my terminal after showing the report tables. Strange enough, I cannot find a running python process.

**Comment by jefftemplon** [comment]
Hi,
I have this issue now with the current version (just now did pip install) and python 2.7.15 (current homebrew version) - what gives?

**Comment by bvbmedia** [comment]
Although the patch provided by @bdillahu prevented from showing the error the application did not do the task.

The real fix for me was to clone the repository and use the develop branch:
```
git clone git@github.com:kdeldycke/maildir-deduplicate.git;
cd maildir-deduplicate;
python ./setup.py develop
```

**Comment by sehargul-123** [comment]
Traceback (most recent call last):
  File "DeepSpeech.py", line 11, in <module>
    import absl.app
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in <module>
    from absl import flags
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/__init__.py", line 41, in <module>
    from absl.flags import _defines
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in <module>
    from absl.flags import _flagvalues
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 26, in <module>
    from apt.package import Package
  File "/usr/lib/python3/dist-packages/apt/package.py", line 24, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'

Original exception was:
Traceback (most recent call last):
  File "DeepSpeech.py", line 11, in <module>
    import absl.app
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in <module>
    from absl import flags
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/__init__.py", line 41, in <module>
    from absl.flags import _defines
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in <module>
    from absl.flags import _flagvalues
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in <module>
    import logging
  File "/home/sehar/DeepSpeech/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/__init__.py", line 92, in <module>
    from absl.logging import converter
  File "/home/sehar/venv/lib/python3.6/site-packages/absl/logging/converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'

**Comment by sehargul-123** [comment]
I got this error while running my run file for training my model
