### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by bonds** [kdeldycke/maildir-deduplicate#61]
I'm scanning a 500K message collection, which I suspect is 75% dupes from various IMAP syncs gone awry. About 1/4 through I always get a crash with this output:

````
Traceback (most recent call last):                                                                          File "/home/scott/.local/bin/mdedup", line 11, in <module>
    load_entry_point('maildir-deduplicate==2.2.0', 'console_scripts', 'mdedup')()
  File "/home/scott/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__                 return self.main(*args, **kwargs)
  File "/home/scott/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/scott/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/scott/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/scott/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return ctx.invoke(self.callback, **ctx.params)                                               [56/272]
  File "/home/scott/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/scott/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/scott/.local/lib/python3.6/site-packages/maildir_deduplicate/cli.py", line 206, in deduplicate                                                                                                          dedup.add_maildir(maildir)
  File "/home/scott/.local/lib/python3.6/site-packages/maildir_deduplicate/deduplicate.py", line 523, in
add_maildir
    mail_hash = mail.hash_key
  File "/home/scott/.local/lib/python3.6/site-packages/boltons/cacheutils.py", line 658, in __get__          value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/scott/.local/lib/python3.6/site-packages/maildir_deduplicate/mail.py", line 138, in hash_key
    return hashlib.sha224(self.canonical_headers).hexdigest()
  File "/home/scott/.local/lib/python3.6/site-packages/boltons/cacheutils.py", line 658, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)                                              File "/home/scott/.local/lib/python3.6/site-packages/maildir_deduplicate/mail.py", line 157, in canonical_headers
    canonical_value = self.canonical_header_value(header, value)
  File "/home/scott/.local/lib/python3.6/site-packages/maildir_deduplicate/mail.py", line 187, in canonical_header_value
    value = re.sub(r'\s+', ' ', value).strip()
  File "/usr/local/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
````
It would be nicer if the malformed email I presume is causing this was skipped with a warning instead of crashing the app. Or, if there were some way to get the app to print out the path of the email its checking before checking it (maybe I'll pipe it to a log file), so after a crash I can go back and remove the problematic email and try again.

I'm running maildir-deduplicate f1c6ff25b80c6c1a4dc2dc7a65b34d808b0b7733 on OpenBSD 6.1-stable with Python 3.6.

**Comment by dancingbigbear** [comment]
I've encountered the same error. I could provide the mail that caused it.

**Comment by bonds** [comment]
Found a workaround. I ran maildir-deduplicate to generate hashes a file at a time, and when it errors I add that to a list of problematic files:

````
find . -type f | xargs -I@ sh -c "if ! ~/.local/bin/mdedup hash @ >/dev/null 2>&1; then echo @; fi" > ~/list_of_badly_encoded_email.txt
````
Then I moved those files to a separate directory so I can run maildir-deduplicate on the remaining, good email files.

**Comment by rixx** [comment]
This issue still occurs on the current master branch.

**Comment by WeeBull** [comment]
Still hitting this. Just took a look at the messages its complaining about (thanks for the sorting method @bonds ), and they're all latin-1 encoded e-mails with non-ASCII characters in.

For example: 
    "Date: Wed, 28 Jan   Hora est. del **Pacífico** de SA"
or
    "Subject: Fill in our survey and you could win **£100**. "

Looking at the code, I'm a little confused.

        @staticmethod
        def canonical_header_value(header, value):
            header = header.lower()
            # Problematic when reading utf8 emails
            # this will ensure value is always string
            if isinstance(value, bytes):
                value = value.decode('utf-8', 'replace')
            value = re.sub(r'\s+', ' ', value).strip()

My reading is that in Python3 everything is an instance of bytes, so the decode should run. It would fail because it's not decoding UTF-8, but the `replace` error handler should still mean it returns a string.

I'll insert some error handling in a bit an re-run, but I'm currently got it working on a large mail database.

**Comment by dschrempf** [comment]
Just wanted to add that I also encountered this error and that the fork https://github.com/baip/maildir-deduplicate works. After hashing the mails, a lot of (unnecessary?) output was produced similar to

    ...
    ---
    ---
    ---
    ---
    ...

and also

    Check that mail differences are within the limits.
    Deleting all mails strictly newer than the 1563611837 timestamp...
    ....

**Comment by kdeldycke** [comment]
Issue as been fixed by merging https://github.com/kdeldycke/maildir-deduplicate/pull/64 upstream.
