### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by LeonB** [kdeldycke/maildir-deduplicate#8]
I get a memory error on a maildir with 838 emails:

```
Processing 838 mails in info/Maildir/.INBOX.leveranciers ...Trimmed Subject to Betaling ontvangen
Trimmed Subject to Bestelbevestiging
....Trimmed Subject to Welkom bij Golfsets!
Traceback (most recent call last):
  File "maildir-deduplicate.py", line 554, in <module>
    main()
  File "maildir-deduplicate.py", line 500, in main
    duplicates_run(opts, maildir_paths)
  File "maildir-deduplicate.py", line 518, in duplicates_run
    mail_count += collate_folder_by_hash(mails_by_hash, maildir, opts.message_id)
  File "maildir-deduplicate.py", line 299, in collate_folder_by_hash
    for mail_id, message in mail_folder.iteritems():
  File "/usr/lib/python2.7/mailbox.py", line 126, in iteritems
    value = self[key]
  File "/usr/lib/python2.7/mailbox.py", line 82, in __getitem__
    return self.get_message(key)
  File "/usr/lib/python2.7/mailbox.py", line 337, in get_message
    msg = MaildirMessage(f)
  File "/usr/lib/python2.7/mailbox.py", line 1427, in __init__
    Message.__init__(self, message)
  File "/usr/lib/python2.7/mailbox.py", line 1399, in __init__
    self._become_message(email.message_from_file(message))
  File "/usr/lib/python2.7/email/__init__.py", line 66, in message_from_file
    return Parser(*args, **kws).parse(fp)
  File "/usr/lib/python2.7/email/parser.py", line 71, in parse
    feedparser.feed(data)
  File "/usr/lib/python2.7/email/feedparser.py", line 157, in feed
    self._call_parse()
  File "/usr/lib/python2.7/email/feedparser.py", line 161, in _call_parse
    self._parse()
  File "/usr/lib/python2.7/email/feedparser.py", line 375, in _parsegen
    payload = payload[:-len(mo.group(0))]
MemoryError
```

**Comment by kdeldycke** [comment]
Fixed in 62e33f414424ca35bc775accbd28c0ce376ab11b .
